# Generated by Django 6.0.6 on 2026-06-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_starts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='starts',
            new_name='stars',
        ),
    ]
